CREATE TABLE chatbot_app.ecommerce_users (
    user_id VARCHAR(255) PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    email VARCHAR(255),
    password_salt VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    shopping_budget NUMERIC(38, 2) NOT NULL DEFAULT 15000,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    email_verification_code_hash VARCHAR(255),
    email_verification_expires_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX idx_ecommerce_users_username
    ON chatbot_app.ecommerce_users (username);

CREATE UNIQUE INDEX idx_ecommerce_users_email
    ON chatbot_app.ecommerce_users (email);

CREATE TABLE chatbot_app.admin_users (
    admin_id VARCHAR(255) PRIMARY KEY,
    full_name VARCHAR(255),
    password_salt VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE chatbot_app.customer_orders (
    order_id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    total_amount NUMERIC(38, 2) NOT NULL,
    order_time TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_customer_orders_user
        FOREIGN KEY (user_id)
        REFERENCES chatbot_app.ecommerce_users (user_id)
);

CREATE INDEX idx_customer_orders_user_time
    ON chatbot_app.customer_orders (user_id, order_time DESC);

CREATE TABLE chatbot_app.order_items (
    item_id VARCHAR(255) PRIMARY KEY,
    order_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(38, 2) NOT NULL,
    CONSTRAINT fk_order_items_customer_order
        FOREIGN KEY (order_id)
        REFERENCES chatbot_app.customer_orders (order_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_order_items_order_id
    ON chatbot_app.order_items (order_id);

CREATE TABLE chatbot_app.tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    order_id VARCHAR(255),
    issue_type VARCHAR(50),
    state VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    refund_amount NUMERIC(38, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tickets_user
        FOREIGN KEY (user_id)
        REFERENCES chatbot_app.ecommerce_users (user_id),
    CONSTRAINT fk_tickets_order
        FOREIGN KEY (order_id)
        REFERENCES chatbot_app.customer_orders (order_id)
);

CREATE INDEX idx_tickets_user_updated
    ON chatbot_app.tickets (user_id, updated_at DESC);

CREATE INDEX idx_tickets_status_updated
    ON chatbot_app.tickets (status, updated_at DESC);

CREATE INDEX idx_tickets_duplicate_lookup
    ON chatbot_app.tickets (user_id, order_id, issue_type);

CREATE INDEX idx_tickets_order_status_updated
    ON chatbot_app.tickets (user_id, order_id, status, updated_at DESC);

CREATE TABLE chatbot_app.ticket_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    item_id VARCHAR(255) NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    price NUMERIC(38, 2) NOT NULL,
    CONSTRAINT fk_ticket_items_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES chatbot_app.tickets (ticket_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_ticket_items_ticket_id
    ON chatbot_app.ticket_items (ticket_id);

CREATE TABLE chatbot_app.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT,
    user_id VARCHAR(255) NOT NULL,
    sender VARCHAR(50) NOT NULL,
    message VARCHAR(2000) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_chat_messages_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES chatbot_app.tickets (ticket_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_chat_messages_user
        FOREIGN KEY (user_id)
        REFERENCES chatbot_app.ecommerce_users (user_id)
);

CREATE INDEX idx_chat_messages_user_timestamp
    ON chatbot_app.chat_messages (user_id, timestamp DESC);

CREATE INDEX idx_chat_messages_ticket_timestamp
    ON chatbot_app.chat_messages (ticket_id, timestamp);
