CREATE TABLE customer_orders (
    order_id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255),
    total_amount NUMERIC(38, 2)
);

CREATE TABLE order_items (
    item_id VARCHAR(255) PRIMARY KEY,
    order_id VARCHAR(255),
    name VARCHAR(255),
    price NUMERIC(38, 2),
    CONSTRAINT fk_order_items_customer_order
        FOREIGN KEY (order_id)
        REFERENCES customer_orders (order_id)
);

CREATE TABLE tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    order_id VARCHAR(255),
    issue_type VARCHAR(50),
    state VARCHAR(50),
    status VARCHAR(50),
    refund_amount NUMERIC(38, 2),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE ticket_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT,
    item_id VARCHAR(255),
    item_name VARCHAR(255),
    price NUMERIC(38, 2),
    CONSTRAINT fk_ticket_items_ticket
        FOREIGN KEY (ticket_id)
        REFERENCES tickets (ticket_id)
);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT,
    user_id VARCHAR(255),
    sender VARCHAR(50),
    message VARCHAR(2000),
    timestamp TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_tickets_user_status_updated
    ON tickets (user_id, status, updated_at);

CREATE INDEX idx_tickets_duplicate_lookup
    ON tickets (user_id, order_id, issue_type);

CREATE INDEX idx_ticket_items_ticket_id
    ON ticket_items (ticket_id);

CREATE INDEX idx_chat_messages_user_timestamp
    ON chat_messages (user_id, timestamp);
